### ISSUE TITLE
doctor will crash in a non-graceful way in cases where it hasn't been able to collect stats

### ISSUE THREAD

**Issue by davidmarkclements** [nearform/node-clinic-doctor#112]
The following has no issues, works fine:
```sh
clinic doctor -- node -e "setTimeout(()=>console.log('hi'), 100)"
```

There are two cases that throw different errors.

This fails:
```sh
clinic doctor -- node -e "setTimeout(()=>console.log('hi'), 10)"
```
With this error:

```
/usr/local/lib/node_modules/clinic/node_modules/distributions/distributions/binomial.js:17
    throw TypeError('size must be positive');
    ^

TypeError: size must be positive
    at new BinomialDistribution (/usr/local/lib/node_modules/clinic/node_modules/distributions/distributions/binomial.js:17:11)
    at analyseHandles (/usr/local/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/analyse-handles.js:63:20)
    at /usr/local/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:60:18
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:3874:9
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:980:24)
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:958:16
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:3871:13
    at Endpoint.finish (/usr/local/lib/node_modules/clinic/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:313:30)
```

This fails:
```sh
clinic doctor -- node -e "setTimeout(()=>console.log('hi'), 1)"
```
With this error:

```
/usr/local/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:42
      processStat[intervalIndex[0]].timestamp,
                                    ^

TypeError: Cannot read property 'timestamp' of undefined
    at /usr/local/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:42:37
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:3874:9
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:980:24)
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:958:16
    at /usr/local/lib/node_modules/clinic/node_modules/async/dist/async.js:3871:13
    at Endpoint.finish (/usr/local/lib/node_modules/clinic/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Endpoint.emit (events.js:208:7)
```

**Comment by mafintosh** [comment]
better error, https://github.com/nearform/node-clinic-doctor/pull/116
