### ISSUE TITLE
Error: premature close

### ISSUE THREAD

**Issue by rgadda** [nearform/node-clinic-doctor#142]
Getting the below error when I shutdown my server and clinic doctor should be Analyzing the results
```
/usr/local/lib/node_modules/clinic/bin.js:237
      if (err) throw err
               ^

Error: premature close
    at MultiStream.onclose (/usr/local/lib/node_modules/clinic/node_modules/end-of-stream/index.js:47:67)
    at MultiStream.emit (events.js:187:15)
    at MultiStream.destroy (/usr/local/lib/node_modules/clinic/node_modules/multistream/index.js:65:8)
    at DestroyableTransform.onClose (/usr/local/lib/node_modules/clinic/node_modules/multistream/index.js:111:12)
    at Object.onceWrapper (events.js:273:13)
    at DestroyableTransform.emit (events.js:187:15)
    at /usr/local/lib/node_modules/clinic/node_modules/through2/through2.js:20:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Steps followed to hit this error:
1.  ``` clinic doctor -- yarn start ``` -- starts the app as expected
2. ``` autocannon -c 10 -p 5 -d 10 http://localhost:5050/login ``` using autocannon to hit /login
3. Response from autocannon 
```
Running 10s test @ http://localhost:5050/login
10 connections with 5 pipelining factor

Stat         Avg    Stdev   Max
Latency (ms) 146.52 291.59  1572.72
Req/Sec      66.2   12.23   78
Bytes/Sec    281 kB 52.5 kB 331 kB

662 requests in 10s, 2.81 MB read
```
4. shutting off the app using Cmd+C
5. Clinic Doctor throws back the error.

**Comment by mcollina** [comment]
You are running doctor against yarn, not your server. Could you try that?

**Comment by mcollina** [comment]
closing for no activity. Feel free to reopen if you still experience problems.

**Comment by gajus** [comment]
Related to https://github.com/nearform/node-clinic/issues/41
